name = "vlad"
author = "rho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ff374f0892ad510dd3d613c9d7630e7c5003d0da145efb14f6c835819162e87"

[versions]
fabric = "0.18.1"
minecraft = "1.21.2"
