name = "vlad"
author = "rho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c683b194ad4dd06e90a87f32ce183bca8425a6f678db53f06c89ee08a196911"

[versions]
fabric = "0.18.1"
minecraft = "1.21.2"
