name = "home"
author = "rho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e15b77f3f05970c72c750fb46ed31ee18fd4cf45a437fa16d837497581219fe3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
