name = "home"
author = "rho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19cf2f631e3c834fcef28b09fa0d1a44bda0fd2fa10663b300113f82b8a16327"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
