name = "Forge 2026 Home Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6719e9aba88006e7258f4e9c3bf7ccf646ec8d439a994ab8cec3622469c803a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
