name = "Forge 2026 Home Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c01d47a1449d8b25b9a832b7e5c006951a6d21c59ca5194d46bf96f7d70f57cc"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
