name = "Create"
author = "rhododendrhon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "698ec9da8a990053384573aa577ca5f1c3d1d02f24631c13bbd827bc4c9c4577"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
