name = "Create"
author = "rhododendrhon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d92b952fe16b8b52ec1ce434eefcf8d6820ad70e996fa8002e5dd993c7794ae4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
